### ISSUE TITLE
Invoke-CredentialsInjection doesn't work anymore?

### ISSUE THREAD

**Issue by talboren** [PowerShellMafia/PowerSploit#203] opened 2016-12-14 14:21 UTC
Hey,

First command I ran:
Invoke-CredentialsInjection -ExstingWinLogon -UserName "FAKEUSER" -Password "TEST" -DomainName "FAKEDOMAIN"
which yields:
 + CategoryInfo          : OperationStopped: (Couldn't obtain...rocess ID:
9536:String) [], RuntimeException
 + FullyQualifiedErrorId : Couldn't obtain the handle for process ID: 9536

while
Invoke-CredentialsInjection -NewWinLogon -UserName "FAKEUSER" -Password "TEST" -DomainName "FAKEDOMAIN"
just yields:
WARNING: Unable to get SYSTEM token
Created winlogon process to call LsaLogonUser in. Kill ProcessID  when done imp
ersonating.
Execute: Stop-Process  -force
And get stuck.

Is this script not supported anymore?

**Comment by HarmJ0y** [comment] 2016-12-15 19:23
Are you running in a high integrity process?

**Comment by talboren** [comment] 2016-12-15 19:26
Both powershell as Administrator and powershell with low privilieges

בתאריך יום ה׳, 15 בדצמ' 2016, 21:23, מאת HarmJ0y ‏<notifications@github.com

**Comment by HarmJ0y** [comment] 2016-12-15 19:34
As the code attempts to inject into an existing (or new) winlogon.exe process running as SYSTEM, you need elevated privileges. Even if you're an administrator you will need to run in a high integrity context. You can determine this with `whoami /groups` and checking the last entry.

**Comment by talboren** [comment] 2016-12-16 10:45
Running powershell with psexec as system will solve this issue?

בתאריך יום ה׳, 15 בדצמ' 2016, 21:34, מאת HarmJ0y ‏<notifications@github.com

**Comment by talboren** [comment] 2016-12-18 08:29
Hey @HarmJ0y 
Running PowerShell as System with PSexec (psexec -s -i powershell.exe) and invoking "Invoke-CredentialsInjection" still won't work.
Trying it with NewWinLogon just returns the same as I typed before (except this time I don't get the yellow warning message saying "WARNING: Unable to get SYSTEM token")
Trying it with the ExisitingWinLogon I get 2 different erros:
1. When I try using my real domain as the DomainName parameter I receive

> ERROR_LOGON_FAILURE
> 1326 (0x52E)
> The user name or password is incorrect.

2. When I try using a fake domain as the DomainName parameter I receive:

> ERROR_NO_LOGON_SERVERS
> 1311 (0x51F)
> There are currently no logon servers available to service the logon request.


Please let me know your opinion.

**Comment by okazymyrov** [comment] 2017-02-15 00:05
I have tested the script from the dev brunch on Windows 10.0.14393. It works fine. I have got ERROR_LOGON_FAILURE when typed wrong credentials.

**Comment by FuzzySecurity** [comment] 2017-07-17 20:40
I am unable to reproduce this and I just tested it in Win7 & Win10RS2 as I was fixing a casting issue. Please reopen if the issue persists and provide a detailed overview of the commands you used and privilege level of the user account. Also please use the Dev branch version till it is merged into master.

**Closed by FuzzySecurity** 2017-07-17 20:40 UTC
